---
title: "Day 3 R"
author: "Yucheng Zhu"
date: "9/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Data
```{r}
generation <- read.csv(here::here("data/generation.csv"),
                       stringsAsFactors = FALSE)

imports <- read.csv(here::here("data/imports.csv"), 
                    stringsAsFactors = F)
```

```{r}
str(generation)

class(generation$datetime)
class(imports$datetime)
```

## Converting datetime using lubridate
```{r}
library(lubridate)
generation$datetime <- as_datetime(generation$datetime)
class(generation$datetime)
head(generation$datetime)

imports$datetime <- as_datetime(imports$datetime)
class(imports$datetime)
head(imports$datetime)
```

## Reshaping Data
```{r}
head(generation)

library(reshape2)
long_gen <- melt(generation, id.vars = "datetime",
                 variable.name = "source",
                 value.name = "usage")
head(long_gen)
long_gen[order(long_gen$datetime)[1:20],]

```


## Merging Data
```{r}
merged_energy <- merge(generation, imports, by = "datetime")
dim(merged_energy)
head(merged_energy)
head(imports)
```

## Reshaping
```{r}

long_merged_energy <- melt(merge_energy, id.vars = "datetime",
                          variable.name = "source",
                          value.name = "usage")
head(long_merged_energy)
long_merged_energy[order(long_gen$datetime)[1:20],]

```

## dplyr
```{r}
library(dplyr)

tmp <- select(merged_energy, biogas, biomass, geothermal, solar)
names(tmp)

tmp <- select(merged_energy, -biogas, -biomass, -geothermal, -solar)
names(tmp)

tmp <- select(merged_energy, contains("hydro"), starts_with("bio"))
names(tmp)

tmp <- filter(merged_energy, imports > 7000)
nrow(tmp)
head(tmp)

tmp <- filter(merged_energy, imports > 7000, natural_gas < 7000)
nrow(tmp)
head(tmp)

tmp <- mutate(long_merged_energy, log_usage = log(usage))
head(tmp)

tmp <- mutate(long_merged_energy, log_usage = log(usage), usage2 = usage^2, usage3 = usage^3)
head(tmp)
```

## Summarize

```{r}
summarize(long_merged_energy, total = sum (usage, na.rm = T))

summarize(long_merged_energy, mean_cons = mean(usage, na.rm = T))

```

## Pipe
```{r}
long_merged_energy %>%
  filter(source == "geothermal") %>%
  select(-datetime) %>%
  mutate(log_usage = log(usage)) %>%
  summarize(mean_log_usage = mean(log_usage, na.rm = T))

merged_energy %>% 
  select(-datetime) %>%  ##droped datatime variable
  mutate(total_usage = rowSums(., na.rm = T)) %>% ## . -> stand for the DF 
  summarize(total_usage = sum(total_usage, na.rm = T))

merged_energy %>%
  select(contains("hydro")) %>%
  mutate(total_hydro = rowSums(., na.rm = T)) %>%
  summarize(mean_hydro = mean(total_hydro, na.rm = T))

```

## Group by
```{r}
long_merged_energy %>% 
  group_by(source) %>% 
  summarize(sum_usage = sum(usage, na.rm = T))

merged_energy %>% 
  select(datetime, contains("hydro"), contains("bio")) %>% 
    ## select to choose columns
  melt(id.vars = "datetime",
       variable.name = "source",
       value.name = "usage") %>% 
  group_by(source) %>% 
  summarize(mean_usage = mean(usage, na.rm = T))


long_merged_energy %>%
  filter(source %in% c("large_hydro","small_hydro", "biogas","biomass")) %>%
    ## filter to choose rows
    ## %in %
  group_by(source) %>%
  summarise(mean_usage = mean(usage, na.rm = T))

```













